# Generated by Django 4.1 on 2022-08-21 07:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Chat_Bot', '0002_rename_name_register_uname'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='register',
            name='uname',
        ),
    ]
