# Generated by Django 4.1 on 2022-08-21 07:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Chat_Bot', '0004_registration_delete_register'),
    ]

    operations = [
        migrations.RenameField(
            model_name='registration',
            old_name='gender',
            new_name='gen',
        ),
    ]
