# Generated by Django 4.1 on 2022-08-21 07:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Chat_Bot', '0005_rename_gender_registration_gen'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='registration',
            name='sre',
        ),
    ]
