# Generated by Django 4.1 on 2022-08-21 08:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Chat_Bot', '0006_remove_registration_sre'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='registration',
            name='sub',
        ),
    ]
