# Generated by Django 4.1 on 2022-12-11 06:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Chat_Bot', '0007_remove_registration_sub'),
    ]

    operations = [
        migrations.AddField(
            model_name='registration',
            name='phone',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
