# Generated by Django 4.1 on 2022-12-11 07:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Chat_Bot', '0009_rename_dept_registration_meal_preference'),
    ]

    operations = [
        migrations.RenameField(
            model_name='registration',
            old_name='meal_preference',
            new_name='dep',
        ),
    ]
