# Generated by Django 4.1 on 2022-12-11 09:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Chat_Bot', '0010_rename_meal_preference_registration_dep'),
    ]

    operations = [
        migrations.AddField(
            model_name='registration',
            name='adno',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
