# Generated by Django 4.1 on 2022-12-11 09:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Chat_Bot', '0011_registration_adno'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='registration',
            name='age',
        ),
        migrations.RemoveField(
            model_name='registration',
            name='gen',
        ),
        migrations.RemoveField(
            model_name='registration',
            name='username',
        ),
    ]
