# Generated by Django 4.1 on 2022-12-18 06:39

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('Chat_Bot', '0012_remove_registration_age_remove_registration_gen_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='registration',
            name='email',
        ),
        migrations.RemoveField(
            model_name='registration',
            name='name',
        ),
        migrations.RemoveField(
            model_name='registration',
            name='password',
        ),
        migrations.AddField(
            model_name='registration',
            name='gen',
            field=models.CharField(choices=[('1', 'Male'), ('2', 'Female'), ('3', 'Others')], default='1', max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='registration',
            name='user',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='registration',
            name='dep',
            field=models.CharField(choices=[('1', 'BCA'), ('2', 'BBA'), ('3', 'B.COM With Computer Application'), ('4', 'B.COM With Finance'), ('5', 'B.COM With Co-Operation'), ('6', 'BA English Literature'), ('7', 'BA Multimedia'), ('8', 'B.SC Food Technology'), ('9', 'B.SC Micro Biology'), ('10', 'B.SC Bio Chemistry'), ('11', 'M.COM'), ('12', 'M.SC Food Technology'), ('13', 'M.SC Microbiology')], default='1', max_length=100),
        ),
    ]
