# Generated by Django 4.1 on 2022-12-18 07:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Chat_Bot', '0013_remove_registration_email_remove_registration_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='registration',
            name='gen',
            field=models.CharField(choices=[('1', 'Male'), ('2', 'Female'), ('3', 'Others')], default='1', max_length=10),
        ),
    ]
