# Generated by Django 4.1 on 2022-12-18 07:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Chat_Bot', '0014_alter_registration_gen'),
    ]

    operations = [
        migrations.AlterField(
            model_name='registration',
            name='gen',
            field=models.CharField(choices=[('f', 'Male'), ('m', 'Female'), ('o', 'Others')], default='f', max_length=10),
        ),
    ]
