# Generated by Django 4.1 on 2022-12-29 08:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Chat_Bot', '0015_alter_registration_gen'),
    ]

    operations = [
        migrations.CreateModel(
            name='Chatbot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('send', models.CharField(max_length=200, null=True)),
                ('receive', models.CharField(max_length=200, null=True)),
            ],
        ),
    ]
