# Generated by Django 4.1 on 2023-01-14 05:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Chat_Bot', '0017_chatbot_receive1'),
    ]

    operations = [
        migrations.AddField(
            model_name='chatbot',
            name='receive2',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
