# Generated by Django 4.1 on 2023-01-15 05:33

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('Chat_Bot', '0018_chatbot_receive2'),
    ]

    operations = [
        migrations.CreateModel(
            name='internalmarklist',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=200, null=True)),
                ('Register_Number', models.CharField(max_length=200)),
                ('Android_Programming', models.CharField(max_length=200)),
                ('Operating_System', models.CharField(max_length=200)),
                ('Software_Testing', models.CharField(max_length=200)),
                ('Computer_Networks', models.CharField(max_length=200)),
                ('Project', models.CharField(max_length=200)),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='internalexammarklist',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=200, null=True)),
                ('Register_Number', models.CharField(max_length=200)),
                ('Android_Programming', models.CharField(max_length=200)),
                ('Operating_System', models.CharField(max_length=200)),
                ('Software_Testing', models.CharField(max_length=200)),
                ('Computer_Networks', models.CharField(max_length=200)),
                ('Project', models.CharField(max_length=200)),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
