# Generated by Django 4.1 on 2023-01-15 07:05

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('Chat_Bot', '0019_internalmarklist_internalexammarklist'),
    ]

    operations = [
        migrations.CreateModel(
            name='Attendence',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=200, null=True)),
                ('Semester', models.CharField(max_length=200)),
                ('Register_Number', models.CharField(max_length=200)),
                ('From', models.DateField()),
                ('To', models.DateField()),
                ('Attendence_up_to_Jan', models.CharField(max_length=200)),
                ('Attendence_up_to_Feb', models.CharField(max_length=200)),
                ('Attendence_up_to_Mar', models.CharField(max_length=200)),
                ('Attendence_up_to_Apr', models.CharField(max_length=200)),
                ('Attendence_up_to_May', models.CharField(max_length=200)),
                ('Attendence_up_to_Jun', models.CharField(max_length=200)),
                ('Attendence_up_to_Jul', models.CharField(max_length=200)),
                ('Attendence_up_to_Aug', models.CharField(max_length=200)),
                ('Attendence_up_to_Sep', models.CharField(max_length=200)),
                ('Attendence_up_to_Oct', models.CharField(max_length=200)),
                ('Attendence_up_to_Nov', models.CharField(max_length=200)),
                ('Attendence_up_to_Dec', models.CharField(max_length=200)),
                ('Total_Attendence', models.CharField(max_length=200)),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
