# Generated by Django 4.1 on 2023-01-15 09:18

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('Chat_Bot', '0021_remove_attendence_attendence_up_to_apr_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='attendence',
            name='Department',
            field=models.CharField(default='1', max_length=200),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='internalexammarklist',
            name='Department',
            field=models.CharField(default='1', max_length=200),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='internalmarklist',
            name='Department',
            field=models.CharField(default='1', max_length=200),
            preserve_default=False,
        ),
        migrations.CreateModel(
            name='Fee_Payment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=200, null=True)),
                ('Semester', models.CharField(max_length=200)),
                ('Register_Number', models.CharField(max_length=200)),
                ('Department', models.CharField(max_length=200)),
                ('Course_Fee', models.CharField(max_length=200)),
                ('Paid', models.CharField(max_length=200)),
                ('Due', models.CharField(max_length=200)),
                ('Last_Date', models.CharField(max_length=200)),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
