# Generated by Django 4.1 on 2023-01-15 09:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Chat_Bot', '0022_attendence_department_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fee_payment',
            name='Last_Date',
            field=models.DateField(max_length=200),
        ),
    ]
