# Generated by Django 4.1 on 2023-02-04 05:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Chat_Bot', '0023_alter_fee_payment_last_date'),
    ]

    operations = [
        migrations.CreateModel(
            name='Events',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Event', models.CharField(max_length=200)),
                ('Date', models.DateField(max_length=200)),
                ('Description', models.CharField(max_length=200)),
            ],
        ),
    ]
