# Generated by Django 4.1.7 on 2023-03-25 10:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Chat_Bot', '0024_events'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attendence',
            name='Semester',
            field=models.CharField(max_length=250),
        ),
    ]
