# Generated by Django 4.1.7 on 2023-03-25 11:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Chat_Bot', '0025_alter_attendence_semester'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='attendence',
            name='Total_Attendence',
        ),
        migrations.AddField(
            model_name='attendence',
            name='ta',
            field=models.CharField(default=30, max_length=250),
            preserve_default=False,
        ),
    ]
