# Generated by Django 5.1.1 on 2024-11-03 06:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Chat_Bot', '0026_remove_attendence_total_attendence_attendence_ta'),
    ]

    operations = [
        migrations.AlterField(
            model_name='registration',
            name='dep',
            field=models.CharField(choices=[('1', 'B.Tech'), ('2', 'BBA'), ('3', 'B.COM With Computer Application'), ('4', 'B.COM With Finance'), ('5', 'B.COM With Co-Operation'), ('6', 'BA English Literature'), ('7', 'BA Multimedia'), ('8', 'B.SC Food Technology'), ('9', 'B.SC Micro Biology'), ('10', 'B.SC Bio Chemistry'), ('11', 'M.COM'), ('12', 'M.SC Food Technology'), ('13', 'M.SC Microbiology'), ('14', 'B.Tech')], default='1', max_length=100),
        ),
    ]
