# Generated by Django 5.1.1 on 2024-11-03 06:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Chat_Bot', '0027_alter_registration_dep'),
    ]

    operations = [
        migrations.AlterField(
            model_name='registration',
            name='dep',
            field=models.CharField(choices=[('1', 'CSE'), ('2', 'ECE'), ('3', 'CE'), ('4', 'EEE'), ('5', 'ME'), ('6', 'AIML'), ('7', 'M.Tech'), ('8', 'MCA')], default='1', max_length=100),
        ),
    ]
