# Generated by Django 5.1.1 on 2024-11-03 06:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Chat_Bot', '0028_alter_registration_dep'),
    ]

    operations = [
        migrations.AlterField(
            model_name='registration',
            name='dep',
            field=models.CharField(choices=[('1', 'Select Option'), ('2', 'CSE'), ('3', 'ECE'), ('4', 'CE'), ('5', 'EEE'), ('6', 'ME'), ('7', 'AIML'), ('8', 'M.Tech'), ('9', 'MCA')], default='1', max_length=100),
        ),
        migrations.AlterField(
            model_name='registration',
            name='gen',
            field=models.CharField(choices=[('S', 'Select Option'), ('M', 'Male'), ('F', 'Female'), ('O', 'Others')], default='f', max_length=10),
        ),
    ]
