# Generated by Django 5.1.2 on 2025-03-01 06:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Chat_Bot', '0029_alter_registration_dep_alter_registration_gen'),
    ]

    operations = [
        migrations.AlterField(
            model_name='registration',
            name='dep',
            field=models.CharField(choices=[('1', 'CSE'), ('2', 'ECE'), ('3', 'CE'), ('4', 'EEE'), ('5', 'ME'), ('6', 'AIML'), ('7', 'M.Tech'), ('8', 'MCA')], default='1', max_length=100),
        ),
        migrations.AlterField(
            model_name='registration',
            name='gen',
            field=models.CharField(choices=[('M', 'Male'), ('F', 'Female'), ('O', 'Others')], default='f', max_length=10),
        ),
    ]
