# Generated by Django 5.1.2 on 2025-03-20 05:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Chat_Bot', '0030_alter_registration_dep_alter_registration_gen'),
    ]

    operations = [
        migrations.CreateModel(
            name='Faculty',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=100, null=True)),
                ('gender', models.CharField(blank=True, choices=[('MALE', 'male'), ('FEMALE', 'female'), ('OTHERS', 'others')], max_length=10, null=True)),
                ('department', models.CharField(blank=True, choices=[('BCA', 'bca'), ('CS', 'cs'), ('EL', 'el'), ('BCOM', 'bcom')], max_length=25, null=True)),
                ('phno', models.IntegerField(blank=True, null=True)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('password', models.CharField(max_length=10)),
                ('profilepic', models.ImageField(blank=True, null=True, upload_to='profilepic/')),
            ],
        ),
    ]
